apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cd-pipeline-run-1
spec:
  pipelineRef:
    name: cd-pipeline
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipeline-workspace
